@startuml
skinparam ArrowFontStyle plain
skinparam maxMessageSize 100

actor User
participant ":PharmaTracker" as PharmaTracker
participant "<<class>>\nLoggerSetup" as LoggerSetup
participant ":Ui" as Ui
participant ":Storage" as Storage
participant ":Inventory" as Inventory
participant ":CustomerList" as CustomerList
participant "<<class>>\nPharmaTrackerParser" as PTP
participant "c:Command" as Command

User -> PharmaTracker : launch app (main)
activate PharmaTracker

PharmaTracker -> LoggerSetup : init()
activate LoggerSetup
LoggerSetup --> PharmaTracker
deactivate LoggerSetup

create Ui
PharmaTracker -> Ui : new Ui()
activate Ui
Ui --> PharmaTracker
deactivate Ui

create Storage
PharmaTracker -> Storage : new Storage()
activate Storage
Storage --> PharmaTracker
deactivate Storage

PharmaTracker -> Storage : load()
activate Storage
create Inventory
Storage -> Inventory : new Inventory()
activate Inventory
Inventory --> Storage : inventory
deactivate Inventory
Storage --> PharmaTracker : inventory
deactivate Storage

PharmaTracker -> Storage : loadCustomers()
activate Storage
create CustomerList
Storage -> CustomerList : new CustomerList()
activate CustomerList
CustomerList --> Storage : customerList
deactivate CustomerList
Storage --> PharmaTracker : customerList
deactivate Storage

PharmaTracker -> Ui : printWelcomeMessage()
activate Ui
Ui --> PharmaTracker
deactivate Ui

loop continuous execution loop
    PharmaTracker -> Ui : readCommand()
    activate Ui
    User --> Ui : input string
    Ui --> PharmaTracker : fullCommand
    deactivate Ui

    PharmaTracker -> PTP : parse(fullCommand)
    activate PTP

    create Command
    PTP -> Command : instantiate specific command
    activate Command
    Command --> PTP : c
    deactivate Command

    PTP --> PharmaTracker : c
    deactivate PTP

    PharmaTracker -> Command : execute(inventory, ui, customerList)
    activate Command

    note right of Command
        Execution details depend
        on the specific command.
    end note

    Command --> PharmaTracker
    deactivate Command

    PharmaTracker -> Storage : save(inventory)
    activate Storage
    Storage --> PharmaTracker
    deactivate Storage

    PharmaTracker -> Storage : saveCustomers(customerList)
    activate Storage
    Storage --> PharmaTracker
    deactivate Storage

    destroy Command
end

deactivate PharmaTracker
@enduml