@startuml
actor User
participant ":PharmaTracker" as PharmaTracker
participant ":PharmaTrackerParser" as PharmaTrackerParser
participant ":UpdateCommandParser" as UpdateCommandParser
participant "u:UpdateCommand" as UpdateCommand
participant ":Inventory" as Inventory
participant "med:Medication" as Medication
participant ":Ui" as Ui

User -> PharmaTracker : update 1 /q 50
activate PharmaTracker

PharmaTracker -> PharmaTrackerParser : parseCommand("update 1 /q 50")
activate PharmaTrackerParser

create UpdateCommandParser
PharmaTrackerParser -> UpdateCommandParser : new UpdateCommandParser()
activate UpdateCommandParser
return

PharmaTrackerParser -> UpdateCommandParser : parse("1 /q 50")
activate UpdateCommandParser

UpdateCommandParser -> UpdateCommandParser : extractOptionalQuantity()
activate UpdateCommandParser
return quantity

create UpdateCommand
UpdateCommandParser -> UpdateCommand : new UpdateCommand(...)
activate UpdateCommand
return u

return u

return u

PharmaTracker -> UpdateCommand : execute(inventory, ui, customerList)
activate UpdateCommand

UpdateCommand -> Inventory : getMedication(0)
activate Inventory
return med

opt quantity != null
    UpdateCommand -> Medication : setQuantity(50)
    activate Medication
    return
end

UpdateCommand -> Ui : printUpdatedMedicationMessage(med, changes)
activate Ui
return

return

PharmaTracker --> User : displays output
deactivate PharmaTracker
@enduml